
####  Random forest : Collection of many decision trees

* Bagging: each tree use different datatype with replacement

# Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

# Data Loading

In [ ]:
df = pd.read_csv('/content/customer_churn -Roopneet.csv')

In [ ]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes


# EDA - Exploratory Data Analysis

In [ ]:
df.shape

(7043, 21)

In [ ]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
df['MonthlyCharges'].value_counts()

MonthlyCharges
20.05     61
19.85     45
19.95     44
19.90     44
20.00     43
          ..
56.85      1
101.70     1
48.40      1
108.35     1
72.00      1
Name: count, Length: 1585, dtype: int64

In [ ]:
df['TotalCharges'].value_counts()

TotalCharges
           11
20.2       11
19.75       9
20.05       8
19.9        8
           ..
130.15      1
3211.9      1
7843.55     1
2196.3      1
197.4       1
Name: count, Length: 6531, dtype: int64

In [ ]:
#total charges have blank values, we need to replace it with null/nan

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors ='coerce')
df['TotalCharges'].value_counts()

TotalCharges
20.20      11
19.75       9
19.65       8
19.90       8
20.05       8
           ..
130.15      1
3211.90     1
7843.55     1
2196.30     1
197.40      1
Name: count, Length: 6530, dtype: int64

In [ ]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [ ]:
df['TotalCharges'].unique()

array([  29.85, 1889.5 ,  108.15, ...,  346.45,  306.6 , 6844.5 ])

In [ ]:
df.dropna(inplace = True)

In [ ]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(7032, 21)

In [ ]:
df.head(2)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No

In [ ]:
df.drop(columns = ['customerID'], inplace = True)

In [ ]:
df.head(2)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No

# Encoding:

Text to numbers

### Types of encoding

1. Label encoding: each category is replaced by a numebr eg: male = 1 and female = 2

2. One hot encoding: create a new columns for each category with 0 and 1

3. Ordinal encoding: when categories have a natural order

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
col_list = []

for i in df.columns:
  if ((df[i].dtype == 'object') & (i != 'Churn')):
    col_list.append(i)

col_list

['gender',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod']

In [ ]:
for i in col_list:
  df[i] = le.fit_transform(df[i])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   int64
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   int64
 3   Dependents        7032 non-null   int64
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   int64
 6   MultipleLines     7032 non-null   int64
 7   InternetService   7032 non-null   int64
 8   OnlineSecurity    7032 non-null   int64
 9   OnlineBackup      7032 non-null   int64
 10  DeviceProtection  7032 non-null   int64
 11  TechSupport       7032 non-null   int64
 12  StreamingTV       7032 non-null   int64
 13  StreamingMovies   7032 non-null   int64
 14  Contract          7032 non-null   int64
 15  PaperlessBilling  7032 non-null   int64
 16  PaymentMethod     7032 non-null   int64
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   object
dtypes: float64(2), int64(17), object(1)
memory usage: 1.1+ MB

In [ ]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,No
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,No
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,Yes
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,No
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,Yes

# Model Building

#### Dividing into independent and depended

In [ ]:
x = df.iloc[:,:-1]  # indpendednt columns
## [row:row, column:column]
y = df['Churn']

In [ ]:
x

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,2,0,2,2,2,2,1,1,3,84.80,1990.50
7039,0,0,1,1,72,1,2,1,0,2,2,0,2,2,1,1,1,103.20,7362.90
7040,0,0,1,1,11,0,1,0,2,0,0,0,0,0,0,1,2,29.60,346.45
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,306.60
7042,1,0,0,0,66,1,0,1,2,0,2,2,2,2,2,1,0,105.65,6844.50

In [ ]:
y

0        No
1        No
2       Yes
3        No
4       Yes
       ...
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7032, dtype: object

#### Splitting

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size= 0.2, random_state = 42, stratify = y)
# stratify -> taking 50%yes and 50% no value in both train and testing data
# stratify means keep the same proportion of classes in both the trainning and testing data

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100)

In [ ]:
classifier.fit(x_train, y_train)

RandomForestClassifier()

In [ ]:
y_pred = classifier.predict(x_test)
y_pred

array(['No', 'Yes', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_pred, y_test)

0.7882018479033405

In [ ]:
# n_estimators: how manky decision tree we want

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_pred, y_test)
cm

array([[925, 190],
       [108, 184]])

In [ ]:
# decision tree

n = [100,200,300,400,500,600,700,800,900,1000]

accuracy = []
for i in n:
  model = RandomForestClassifier(n_estimators = i, random_state = 43)
  model.fit(x_train, y_train)
  pred = model.predict(x_test)
  a = accuracy_score(y_test, y_pred)*100

  accuracy.append(a)

In [ ]:
d = {'numberof tree': n,
     'acuracy score': accuracy}

df1 = pd.DataFrame(d)
df1

   numberof tree  acuracy score
0            100      78.820185
1            200      78.820185
2            300      78.820185
3            400      78.820185
4            500      78.820185
5            600      78.820185
6            700      78.820185
7            800      78.820185
8            900      78.820185
9           1000      78.820185

### Hyperparameter tuning:

* Hyperparameter truning refers tot he process of selecting optimal values for the different parameter of machine learning

1. gridsearch cv: taking all possible combination of the parameter

2. randomized cv: selecting random parameter

* n_estimator: number of tree in a forest

* max_depth: the maximu depth of each decision tree

* min_sample_split: min no. of sample required to split a node

* min_sample_leaf: min no. of sample required to be at leaf node

* max_feature: no. of features to consider while looking at best split

'sqrt':

log2:

* Bootstrap: ture, false

1. Bootstrap is a method where multiple models are trainged on different random subsets of the training data using bootstrap == sampling with replacement
2. Thier predictions are then combined to produce more accurate result

* Criteria: gini or entropy

In [ ]:
## Grid CV:

# step 1
from sklearn.model_selection import GridSearchCV

# step 2
param_grid = {
    'n_estimators': [100,200,300],
    'max_depth':[None, 5, 10],
    'min_samples_leaf': [1,2,4],
    'criterion': ['gini', 'entropy'],
    'bootstrap': [True, False]
}

# step 3
classifier1 = RandomForestClassifier(random_state = 42)
grid_search = GridSearchCV(estimator = classifier1, param_grid = param_grid, cv = 2)

In [ ]:
# cv - cross validation

grid_search.fit(x_train, y_train)

GridSearchCV(cv=2, estimator=RandomForestClassifier(random_state=42),
             param_grid={'bootstrap': [True, False],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 5, 10],
                         'min_samples_leaf': [1, 2, 4],
                         'n_estimators': [100, 200, 300]})

In [ ]:
grid_search.best_params_

{'bootstrap': True,
 'criterion': 'gini',
 'max_depth': 5,
 'min_samples_leaf': 2,
 'n_estimators': 300}

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
classifier2 = RandomForestClassifier(n_estimators = 300, criterion = 'gini', max_depth = 5,
                                     min_samples_leaf = 2, bootstrap = True, random_state = 42)

In [ ]:
classifier2.fit(x_train, y_train)

RandomForestClassifier(max_depth=5, min_samples_leaf=2, n_estimators=300,
                       random_state=42)

In [ ]:
accuracy_score(y_pred, y_test)

0.7882018479033405

### OOB - Out of Bag


* It is a way to check the performance of the random forest model without using a seperate validation test

In [ ]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,No
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,No
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,Yes
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,No
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,Yes

In [ ]:
# step 1

y = df['Churn']
x1 = df.iloc[:, :-1]

In [ ]:
y

0        No
1        No
2       Yes
3        No
4       Yes
       ...
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7032, dtype: object

In [ ]:
x1

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,2,0,2,2,2,2,1,1,3,84.80,1990.50
7039,0,0,1,1,72,1,2,1,0,2,2,0,2,2,1,1,1,103.20,7362.90
7040,0,0,1,1,11,0,1,0,2,0,0,0,0,0,0,1,2,29.60,346.45
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,306.60
7042,1,0,0,0,66,1,0,1,2,0,2,2,2,2,2,1,0,105.65,6844.50

In [ ]:
# step 2

oobclassifier = RandomForestClassifier(n_estimators = 800, oob_score = True, random_state = 42)

In [ ]:
oobclassifier.fit(x1,y)

RandomForestClassifier(n_estimators=800, oob_score=True, random_state=42)

In [ ]:
## oob_score = Ture -> means the data we left(unseend data) while training is taken into account
## the left of data is fitted using RandomForestClassifier
## which creates three columns index, probability of churn, probability of not churn

In [ ]:
# step 4

oob_data_indices = np.where(oobclassifier.oob_decision_function_[:,1] >= 0.5)
## [:, 1] means first column, i.e. probability of churn
oob_dataset = x1.iloc[oob_data_indices]
oob_dataset

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65
5,0,0,0,0,8,1,2,1,0,0,2,0,2,2,0,1,2,99.65,820.50
8,0,0,1,0,28,1,2,1,0,0,2,2,2,2,0,1,2,104.80,3046.05
13,1,0,0,0,49,1,2,1,0,2,2,0,2,2,0,1,0,103.70,5036.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7010,0,1,1,0,1,1,2,1,0,0,0,0,0,0,0,1,2,74.45,74.45
7018,1,0,1,1,1,1,0,1,0,0,0,0,0,0,0,1,3,70.65,70.65
7029,0,1,0,0,6,0,1,0,0,0,0,0,2,2,0,1,2,44.40,263.05
7032,1,1,0,0,1,1,2,1,0,0,0,0,0,0,0,1,2,75.75,75.75
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,306.60

In [ ]:
print(oobclassifier.oob_score_)

0.7919510807736063

In [ ]:
oob_probs = pd.DataFrame(
    oobclassifier.oob_decision_function_,
    columns=oobclassifier.classes_
)

oob_probs

            No       Yes
0     0.329073  0.670927
1     0.989726  0.010274
2     0.517361  0.482639
3     0.954064  0.045936
4     0.275510  0.724490
...        ...       ...
7027  0.886288  0.113712
7028  0.778571  0.221429
7029  0.779720  0.220280
7030  0.254181  0.745819
7031  0.759322  0.240678

[7032 rows x 2 columns]

### ROC and AUC

* it will give probability

* how do we know 0.3 means no and 0.9 means yes -> that is where roc and auc comes


ROC - Reciver operating characteristics: is test of different the threshold value

* A graph that show how well the model seperate yes or no across all the threshold vlaues

* It draws a graph between true positive rate and false positive rate

x axis - false positive rate

y axis - true positive rate: (sensitivity) out of all actual poisitive, how many did the model correctly indentify as positive

* specificity: true negative rate: out of all actual negative, how many did the model correctly identify as negative

* roc tells, if I change my cutoof, how good is my model at catching positive value without catching too many false values

AUC score

In [ ]:
from sklearn.metrics import roc_auc_score, roc_curve

In [ ]:
y_pred = classifier2.predict(x_test)[:,-1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed